;; -*- mode: eask; lexical-binding: t -*-

(package "sdml-ts-mode"
         "0.2.1"
         "Major mode for SDML")

(website-url "https://github.com/sdm-lang/emacs-sdml-ts-mode")
(keywords "languages" "tools")

(package-file "sdml-ts-mode.el")
(files "sdml-mode-*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "tree-sitter")
(depends-on "tree-sitter-indent")
