name: Emacs Eask

on:
  push:
    paths-ignore: ["LICENSE*", "**.md", "**.org", ".mise.toml"]

  pull_request:
    paths-ignore: ["LICENSE*", "**.md", "**.org", ".mise.toml"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version: [29.1, 29.4, 30.2, snapshot]

    steps:
      - name: Check out the source code
        uses: actions/checkout@v5

      - name: Install Emacs
        uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Install Eask
        uses: emacs-eask/setup-eask@master
        with:
          version: "snapshot"

      - name: Analyze package
        run: eask analyze

      - name: Create package
        run: eask package

      - name: Install all packages
        run: eask install

      - name: Compile package
        run: eask compile

      - name: Generate package docs
        run: eask docs
